### ISSUE TITLE
Getting GRAPHQL_PARSE_FAILED  when object key has a dash

### ISSUE THREAD

**Issue by brunolemos** [taion/graphql-type-json#102]
It doesn't seem to support dashes, do you know how to fix this?

For example: `{ myKey: true, my-key: false }` (ERROR on `my-key`)

I get a 400 Bad Request and `GRAPHQL_PARSE_FAILED`: 
```json
{"errors":[{"message":"Syntax Error: Invalid number, expected digit but got: \"w\".","locations":[{"line":1,"column":260}],"extensions":{"code":"GRAPHQL_PARSE_FAILED"}}]}
```

I'm using apollo-server-micro.

![image](https://user-images.githubusercontent.com/619186/58447023-61e27380-80d9-11e9-8ca0-22a246eceb11.png)

![image](https://user-images.githubusercontent.com/619186/58447035-6b6bdb80-80d9-11e9-8de2-b94db8dc6d45.png)

**Comment by taion** [comment]
Right, that's just not valid GraphQL. You can use a variable if you need to pass in such a value.

**Comment by brunolemos** [comment]
Thanks, using variables worked.
