### ISSUE TITLE
Variable "$features" of type "JSON" used in position expecting type "JSON".

### ISSUE THREAD

**Issue by sandervanhooft** [taion/graphql-type-json#12]
Hi,

I am getting this weird error when using JSON as input on a mutation:
```
"GraphQL error: Variable "$features" of type "JSON" used in position expecting type "JSON"."
```

I have followed the [Apollo docs](http://dev.apollodata.com/tools/graphql-tools/scalars.html#Using-a-package)  and am able to retrieve JSON. But somehow I seem unable to use it as an input.

Any clue what I'm doing wrong?

Server side schema:
```
    scalar JSON

    createOffer(
      token: String!
      title: String!
      description: String!
      offer_category_id: ID!
      min_price: Float!
      features: JSON
      active: Boolean
    ): Offer
```

Client side mutation:
 ```
const createOfferMutation = gql`
  mutation createOffer(
    $token: String!,
    $offer_category_id:ID!,
    $title: String!,
    $description:String!,
    $min_price:Float!,
    $features: JSON,
    $active:Boolean!
  ){
    createOffer(
      token: $token,
      offer_category_id:$offer_category_id,
      title: $title,
      description: $description,
      min_price: $min_price,
      features: $features,
      active: $active
    ){
        # ...
    }
  }
`;
```

**Comment by taion** [comment]
You most likely have two copies of this library in your build somehow (probably Apollo bundles one, and it may not be the same version as the one you have installed). This pattern works fine for me.

**Comment by JorgeCeja** [comment]
@sandervanhooft Any specifics on how you got `JSON` working on the client-side?

**Comment by sandervanhooft** [comment]
@JorgeCeja I can't remember anything more about this than what's in #225, sorry. I'm dedicated to Laravel now, no longer involved with Apollo/GraphQL.
