### ISSUE TITLE
Document what is GraphQLJSONObject and what is GraphQLJSON

### ISSUE THREAD

**Issue by linonetwo** [taion/graphql-type-json#133]
What are they? String or JS Object?

**Comment by taion** [comment]
Is something missing in the formal descriptions of the types? Is the idea that you just want them in the README?

**Comment by linonetwo** [comment]
No, you didn't mention what they look like in the client side:

For example, GraphQLJSON is like this, but I'm still confused about what GraphQLJSONObject will look like in the client side.

<img width="994" alt="屏幕快照 2019-07-10 下午9 25 35" src="https://user-images.githubusercontent.com/3746270/60972669-4b2a7000-a359-11e9-8cd6-dd9d705f5f6f.png">

**Comment by taion** [comment]
I'm not sure what you mean. As the name suggests, it's a JSON object.

**Comment by linonetwo** [comment]
But as result, `GraphQLJSON` seems like JSON object, since I can pass `{ "a": true }` to it.

Do you mean by using `GraphQLJSONObject` I can pass JSON string to it? like `"{ \"a\": true }"` to it?

**Comment by taion** [comment]
No, it's the reverse. `GraphQLJSON` can take arbitrary JSON values. `GraphQLJSONObject` can _only_ take objects. Something like `3` or `"foo"` are valid for the former, but not the latter.

**Comment by linonetwo** [comment]
Thank you for explanation.

**Comment by lucasconstantino** [comment]
Had the same doubt. Could definitely be documented on README ;)

**Comment by taion** [comment]
Adding a blurb in https://github.com/taion/graphql-type-json/pull/159.

**Comment by wtrocki** [comment]
I was confused as well. @linonetwo thank you so much for posting photo of the example. It really explains a lot. It is not helping that Playground will actually report errors for the scalars so it is hard to even use the API that utilizes JSON object.

**Comment by franz-see** [comment]
@taion the blurb

> GraphQLJSON can represent any JSON-serializable value, including scalars, arrays, and objects. GraphQLJSONObject represents specifically JSON objects, which covers many practical use cases for JSON scalars.

Still isnt that helpful imho. i read that blurb and then i had to google what it actually means. I think that's because when somebody hears JSON, it automatically equates to a JSON Object. Reading from this thread though, this is my understanding 

Given

```
{
   "name": "John Doe",
   "age": 37,
    "dummy": true,
    "dummyValues": [1,2,3]
}
```

That whole object can be represented as `GraphQLJSONObject` or `GraphQLJSON`, while the `"John Doe"`, `37`, `true`, and `[1,2,3]` are `GraphQLJSON` ...did I get that right?

**Comment by taion** [comment]
Yes, that's correct. This is just following the terminology at https://www.json.org/json-en.html.

**Comment by theogravity** [comment]
I still don't get it after reading this thread.

- if you have a field that would be outputted as stringified JSON, you would use `GraphQLJSON`?
- if an object, use `GraphQLJSONObject`?
- or is `GraphQLJSONObject` strictly an object of objects?

**Comment by mattalexander-pantheon** [comment]
> GraphQLJSON can represent any JSON-serializable value, including scalars, arrays, and objects. GraphQLJSONObject represents specifically JSON objects, which covers many practical use cases for JSON scalars.

https://github.com/taion/graphql-type-json/blob/master/README.md

**Comment by JustinTRoss** [comment]
I ran into this same question a few weeks ago, when trying to figure out whether this would be a suitable replacement for AWS AppSync's AWSJSON scalar. It's brutally simple and redundant, but for posterity, would you mind verifying the understanding below is accurate?

## GraphQLJSONObject
### Schema:
```
scalar GraphQLJSONObject
addThought(thought: GraphQLJSONObject: ...
```

### Usage:
_Any JSON stingifiable **object**._

#### Incorrect:
```
addThought({thought: 3});
addThought({thought: "squirrel"});
addThought({thought: () => 3});
addThought({thought: "{ \"animal\": \"dog\" }");
```

#### Correct:
```
addThought({thought: { animal: "dog" });
```

### Resolution:
_Value matches provided value._
`{ animal: "dog" }` resolves to `{ animal: "dog" }`

## GraphQLJSON
### Schema:
```
scalar GraphQLJSON
addThought(thought: GraphQLJSON: ...
```

### Client:
_Any JSON stingifiable value._

#### Incorrect:
```
addThought({thought: () => 3});
```

#### Correct:
```
addThought({thought: 3});
addThought({thought: "squirrel"});
addThought({thought: { animal: "dog" });
addThought({thought: "{ \"animal\": \"dog\" }");
```

### Resolution:
_Value matches provided value exactly._

`3` resolves to `3`
`"squirrel"` resolves to `"squirrel"`
`{ animal: "dog" }` resolves to `{ animal: "dog" }`
`"{ \"animal\": \"dog\" }"` resolves to `"{ \"animal\": \"dog\" }"`
