### ISSUE TITLE
Using JSON as a scalar in buildSchema function of graphql.js

### ISSUE THREAD

**Issue by bharanidharan-k** [taion/graphql-type-json#14]
Can you provide a concrete example of how to use JSON as a scalar while passing the schema to buildSchema function of graphql.js? For example, I need content as a json, something like below.

```
import {
    buildSchema
} from 'graphql';


export default buildSchema(`
  type Query {
    getContent: [Content]
  }
  type Content {
   content: JSON
    type: String
  }
`)

**Comment by taion** [comment]
I don't use this syntax. It should be the same as for any other custom scalar, though.

**Comment by roflc0pter** [comment]
Such a great support.
