### ISSUE TITLE
Can't get GraphQL to recognize the JSON scalar type.

### ISSUE THREAD

**Issue by g-lsh** [taion/graphql-type-json#15]
Hi, I can't get GraphQL to recognize the JSON scalar type.

I followed the [apollo docs] (http://dev.apollodata.com/tools/graphql-tools/scalars.html#Using-a-package)  to define a JSON GraphQL scalar type for my schema:

```javascript

Schema:

    const SchemaDefinition = `
       scalar JSON
       schema {
         query: Query
         mutation: Mutation
      }
    `

    export default [
      SchemaDefinition,
      Query,
      Mutation,
      ...
    ]
```
Test type:
```javascript
    const Test = `
      type Test {
        bodyJson: JSON
     }`
```

Resolver:
  
```javascript

    import GraphQLJSON from 'graphql-type-json'

    const QueryResolver = {
      Query: {
        viewer(root, args, ctx) {
          return User.query()
            .where('id', ctx.state.user)
            .first()
         }
      }
    }

    const scalarJSON = {
      JSON: GraphQLJSON
    }

    export default {
      ...QueryResolver,
      ...ViewerResolver,
      ...scalarJSON
      ...
    }

```

I'm using PostgreSQL and the column I'm querying (body_json) is of data type jsonb.

If I test my schema through GraphiQL, when I return the value straight from the db (I use Knex to query) I get this error message from GraphQL:

`Expected a value of type \"JSON\" but received: [object Object]`

If I use JSON.stringify first on the returned value, I get this error:

`"Expected a value of type \"JSON\" but received: {\"key\":\"test\"}"`

Any suggestion as to what I might be doing wrong?

**Comment by taion** [comment]
This isn't really anything to do with this package directly. Make sure you're following the recommendations on the Apollo side to use custom scalar types appropriately.
