### ISSUE TITLE
unable to query JSON in graphql..is this a known limitation?

### ISSUE THREAD

**Issue by sarora2073** [taion/graphql-type-json#16]
Hi,

First - thanks to whoever works on this package! Not sure why it's not part of a core graphql library but it should be. I've read far and wide on the lack of support for native JSON object support within graphql, and so am guessing the best way currently available is a 3rd party package such as this.

I needed a way to work with schemaless / customer-driven data with varying structures, and so I'm using MongoDB as the schema-less store and was hoping Graphql would "play well" too.
When I attempt to run a graphql query against a JSON type (i.e. an embedded document in my collection), i get a message like so:

"message":"Field \"myQuery" must not have a selection since type \"JSON\" has no subfields.","locations":[{"line":2,"column":37}],"details":null}]}

Is this inability to query the JSON object type natively by GraphQL just a known limitation? 

For now, i'm asking my client app to pull the entire JSON object via a graphql query, and doing further drilling on the client-side, but this introduces additional overhead in many ways, including code bloat on the client app to handle what graphql is ideally suited for.

Please advise if i'm hitting a known limitation of this package with GraphQL, and if so, any better workarounds other than what i'm already doing?

Thank you,

S. Arora

**Comment by taion** [comment]
graphql fundamentally doesn't work that way

**Comment by sarora2073** [comment]
That's what i figured. :-( Thanks for confirming.
