### ISSUE TITLE
Not clear how to use this with .graphql files

### ISSUE THREAD

**Issue by jay-at-avido** [taion/graphql-type-json#17]
Please include an example on how to use this lib with schemas defined in .graphql files and not with javascript notation

Found a discussion on this topic here: 
[http://stackoverflow.com/questions/42353161/how-to-use-graphql-type-json-package-with-graphql](http://stackoverflow.com/questions/42353161/how-to-use-graphql-type-json-package-with-graphql)

**Comment by taion** [comment]
That's an Apollo concept, not a graphql-js one.

**Comment by jay-at-avido** [comment]
Right, but don't you think it's even worth a mention in the read.me? 
Like "if you plan to use this with Apollo GraphQL, please refer to blah blah blah""

I just think that it's a question that will keep popping up due to Apollo's growing popularity

**Comment by taion** [comment]
If you want to PR docs, go for it. Otherwise the answer is "just like any other custom scalar type in whatever system you're using".

**Comment by klebba** [comment]
@jay-jlm I too ran into this issue due to my interest in `graphql-type-json` -- here is a `graphql-js` solution: https://stackoverflow.com/questions/47824603/graphql-custom-scalar-definition-without-graphql-tools

**Comment by shadowbrush** [comment]
The following works for me:

`types.graphql`:

    scalar JSON
    
    type User {
      id: String!
      roles: JSON
    }

`schema.graphql`:

    # import * from './types.graphql'
    
    type Query {
      user(userId: String!): User
    }

Creating the schema:

    import GraphQLJSON from 'graphql-type-json';
    import { importSchema } from 'graphql-import';
    import resolvers from './resolvers';

    const typeDefs = importSchema(path.join(__dirname, 'schema.graphql'));

    const schema = makeExecutableSchema({
      typeDefs,
      resolvers,
    });
    schema.getTypeMap()['JSON'] = GraphQLJSON;
