### ISSUE TITLE
Incompatible with graphql@0.10.0

### ISSUE THREAD

**Issue by hollandThomas** [taion/graphql-type-json#19]
With the new graphql@0.10.0 release, I get the following error message:

`Error: Element.data field type must be Output Type but got: JSON.`

the field in question is simply
```
data: {
  type: GraphQLJSON,
  description: "The element's data.",
},
```

Thanks for looking into this! :)

**Comment by taion** [comment]
you probably have duplicate installed versions of `graphql-js`

**Comment by hollandThomas** [comment]
You are right. Had to remove both graphql and graphql-type-json and add them again with yarn. Thank you!
