### ISSUE TITLE
Parsed objects are not linked to Object.prototype

### ISSUE THREAD

**Issue by joeldouglass** [taion/graphql-type-json#21]
Is there a reason why you're creating a new object with `null` prototype in this section?

`case Kind.OBJECT: {
      const value = Object.create(null);
`

It's causing some of my downstream code to blow up due to missing methods like `hasOwnProperty`.

Could this be changed instead to:

`const value = {};`

**Comment by taion** [comment]
You shouldn't be doing that anyway: http://eslint.org/docs/rules/no-prototype-builtins

Null-prototype is correct for objects used as maps. Upstream GraphQL.js uses this pattern extensively.

**Comment by joeldouglass** [comment]
Thanks. I'm not doing that directly, but unfortunately a 3rd party package I'm using is.
