### ISSUE TITLE
Using query variables for JSON values returns null to resolver

### ISSUE THREAD

**Issue by askogrand** [taion/graphql-type-json#22]
Query:
```
activityGroups: [
     {name: "Set 1", startDate: $startDate},
     {name: "Set 2", startDate: "11/01/16"}
]
```
Query Variables:
```
"startDate": "01/01/16",
```

In graphiql, if I pass in a query variable in, the parseLiteral in graphql-type-json wont resolve the type variable, and simpy returns null.

**Comment by taion** [comment]
The JSON type here is a scalar type. That kind of nesting just doesn't make sense in context.
