### ISSUE TITLE
parseObject does not work for parseLiteral

### ISSUE THREAD

**Issue by lukas-reineke** [taion/graphql-type-json#227]
When I pass a string to to a json field as a variable, I get a correct error message
```
Variable \"$a\" got invalid value \"foo\"; Expected type JSONObject. JSONObject cannot represent non-object value: foo
```

But when I do the same thing inline, without using a variable, I get this error
```
Expected type JSONObject, found \"foo\"; Cannot read property 'forEach' of undefined
```

the `parseObject` function expects a `ast` node

**Comment by taion** [comment]
well, it works, but the error sort of sucks
