### ISSUE TITLE
Graphql key as number with GraphQLJSON

### ISSUE THREAD

**Issue by Raulvv** [taion/graphql-type-json#23]
Good day,

I use GraphQLJSON because I found we have fields in a NoSLQ database named like "90-100", meaning they are numbers and Graphql does not allow numbers as keys.

Question is, GraphQLJSON allows me to retrieve the saved data, but does not allow me to simply do the same in a GraphQLInputObjectType.

Is there a way to get a JSON as a input so I can skip that?

Thanks a lot for the help and the package creation! :)

**Comment by taion** [comment]
GraphQLJSON works just fine as an input object.

**Comment by taion** [comment]
input type rather
