### ISSUE TITLE
JSON type allows using lists at the first level

### ISSUE THREAD

**Issue by pa-bru** [taion/graphql-type-json#25]
With the actual JSON type, you could do this in a graphql type : 
```
type User {
    things: JSON

}
```
and the `things` field could accept an array of json. 
```
[
        { "foo":"bar"},
        { "bar":"baz"}
]
```

But is that what we want ? The good `things`definitiion should be `[JSON]`
If you agree with this, I can do a PR if you want :)

**Comment by taion** [comment]
It's intentional that you can put any valid JSON value here, yes.

**Comment by taion** [comment]
Though if you want to PR something like adding a JSON object type, that would be reasonable.
