### ISSUE TITLE
Upgrade graphql to v0.12.3

### ISSUE THREAD

**Issue by kavink** [taion/graphql-type-json#26]
Would it be possible to upgrade graphql to latest release ?

**Comment by taion** [comment]
It’s not needed. The peer dep range covers the new version. As far as I’m aware everything just works.

**Comment by kavink** [comment]
The issue I see is following, its mainly when I run prod build ```npm run build ``` is I see this error .
Dev build works fine, If I remove this package I can upgrade to latest graphql version. 
```
instanceOf.js:11 Uncaught Error: Cannot use e "__Schema" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

**Comment by kavink** [comment]
@taion ^^

**Comment by taion** [comment]
This package doesn't have any sort of dependency on the `graphql` package. The only dependency here is the listed peer dependency.
