### ISSUE TITLE
Adding assertion or validation to the Scalar

### ISSUE THREAD

**Issue by karloluis** [taion/graphql-type-json#27]
What would it look like if I wanted to ensure that the value is a javascript object and not of any other type?

I have this definition currently under use and if I where to pass, for example, an integer value as the result this would permit it because of the way the type checks occur. My guess is that it will look something like the scalar assertions in the reference implementation (graphql-js) See [this](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js).

**Comment by taion** [comment]
Yeah pretty much. You'd also want the first level of `parseLiteral` to only handle the object case.

**Comment by karloluis** [comment]
Is this something this package is expected to do? If so I could whip up a PR to address it.

**Comment by taion** [comment]
The current behavior of “any valid JSON” is intentional. We could add another export for “JSON object” though – that seems like it could be useful.

**Comment by karloluis** [comment]
Maybe I'm missing something, it seems to me that a for example an array would not be a valid JSON, but would be an object.

I'm interested in understanding your interpretation and working something out.

**Comment by taion** [comment]
An array is totally valid JSON: http://www.json.org/

```
> JSON.parse('[1,2,3]')
[ 1, 2, 3 ]
```

**Comment by karloluis** [comment]
Well I certainly missed that completely. 

In any case I'll give it a shot for the "JSON object".
