### ISSUE TITLE
No validation is done for strings

### ISSUE THREAD

**Issue by Weakky** [taion/graphql-type-json#273]
## Description

Any strings can be returned in a resolver of type `JSON`, although it's not the case for  `JSON.parse`. eg: `{}$`, `!!!![]`, `a`.

The implementation clearly returns the string untouched when it's a string, although `JSON.parse` throws for pretty much anything except a valid json: `{}`, `[]`, ...

Is this expected?

## Expected behavior

Error for everything that `JSON.parse` throws for

**Comment by taion** [comment]
This is intentional. The string '"{}$"' is valid JSON, and is what's represented by that return value. `JSON` and `JSONObject` deal not in JSON strings, but in values that can be serialized as JSON, so literally as objects, &c.
