### ISSUE TITLE
JSONObject cannot represent non-object value

### ISSUE THREAD

**Issue by etc-tiago** [taion/graphql-type-json#278]
Saving data is correct and is not returning any errors. OK.

But taking the record from the database and returning the response to the request is generating the following error:  `JSONObject cannot represent non-object value: [object Object],[object Object],[object Object]`

My model:
```tsx
import { Entity, PrimaryGeneratedColumn, Column, BaseEntity } from 'typeorm';
import { ObjectType, Field, ID } from 'type-graphql';
import { GraphQLJSONObject } from 'graphql-type-json';

@ObjectType()
@Entity({ name: 'medical-templates' })
export class Contents extends BaseEntity {
  @Field(() => ID)
  @PrimaryGeneratedColumn()
  id: string;

  @Field(() => String)
  @Column({ type: 'varchar', length: 100 })
  title: string;

  @Field(() => GraphQLJSONObject)
  @Column({ type: 'json', nullable: true })
  content: any[];
}
```

Is there another type to be used instead of GraphQLJSONObject?

**Comment by taion** [comment]
Looking at this, you probably want `GraphQLList(GraphQLJSONObject)` if you have a list of JSON objects. You could also do `GraphQLJSON` if you want "any JSON-serializable value".
