### ISSUE TITLE
The GraphQLJSONObject cannot be an array

### ISSUE THREAD

**Issue by zachsa** [taion/graphql-type-json#293]
For a GraphQL query that returns `GraphQLJSONObject`, I get an error if the return is an array rather than an object. 

In my resolver:

```
return [{x: 1}]
```
This results in:
```
GraphQLJSONObject cannot represent non-object value: [object Object]
```

**Comment by taion** [comment]
Right, that's the point – it's only supposed to model JSON _objects_. `GraphQLJSON` represents arbitrary JSON values, though.

**Comment by zachsa** [comment]
Okay. Since an array is a valid JSON object I was expecting it to work.

**Comment by zachsa** [comment]
What are the reasons for not supporting arrays as valid json?

**Comment by taion** [comment]
"Object" refers to collections key-value pairs: https://www.json.org/json-en.html

Again, you're looking for `GraphQLJSON`, which is just "any JSON value"

**Comment by ozanmuyes** [comment]
A JavaScript array **is** a JavaScript object though.
