### ISSUE TITLE
Unknown type "JSON"

### ISSUE THREAD

**Issue by tehpsalmist** [taion/graphql-type-json#294]
Hi, I'm wondering if there is a simple answer as to why consumers of my schema would get this error: `Unknown type "JSON"`. My query looks like this:

```graphql
query getStuff ($filter: JSON) {
  stuff(filter: $filter){
    ...
  }
}
```

So, I change the type from `JSON` to `JSONObject` and the schema consumers think that's great. But now my api throws the error `Unknown type "JSONObject"` (before it was working fine with `JSON` as the type). What am I missing here?

**Comment by taion** [comment]
Take a look at https://www.apollographql.com/docs/apollo-server/schema/scalars-enums/#using-a-package
