### ISSUE TITLE
Errors importing

### ISSUE THREAD

**Issue by elie222** [taion/graphql-type-json#33]
When I import like so it works:

```ts
const GraphQLJSON = require('graphql-type-json');
```

When I import like so it doesn't:

```ts
import GraphQLJSON from 'graphql-type-json';
```

The error I get is:

> Error: "JSON" defined in resolvers, but has invalid value "undefined". A resolver's value must be of type object or function.

I verified that `GraphQLJSON` is indeed `undefined` with a `console.log`.

Any ideas?

**Comment by taion** [comment]
This works fine for me. Make sure your import transpilation settings are correct. The type is in fact the direct export. You can check the transpiled import in your code to see what Babel/&c. are doing here. For reference, here is the transpiled code for this package: https://unpkg.com/graphql-type-json@0.2.1/lib/index.js.

**Comment by elie222** [comment]
Thanks. We're using typescript. I wonder if that has anything to do with
it.

**Comment by taion** [comment]
May need to do `import * as GraphQLJSON from ...` then. Or else feel free to contribute a TSD file here.

**Comment by derblitz** [comment]
Is it possible to add GraphqlJSON as default export so it's in line with the example provided? I had the same issue.

**Comment by taion** [comment]
When using ES modules, it is the default export. With CJS and require, I can’t get Babel to give me that result.
