### ISSUE TITLE
GraphQLJSON as a argument type

### ISSUE THREAD

**Issue by juancabrera** [taion/graphql-type-json#4]
Have you used this JSON type as a type for an argument ?. Can't get it working, I have this:

```javascript
entries: {
  type: new GraphQLList(entryType),
  args: {
    query: { type: GraphQLJSON }
  },
  resolve: (obj, args) => client.getEntries(args.query).then(entries => entries.items)
},
```

When I try to pass it a parameter, let's say:

```javascript
{
  entries(query: {'content_type': 'sFzTZbSuM8coEwygeUYes'}) {
    id
    fields
  }
}
```
Got this error:
```javascript
{
  "errors": [
    {
      "message": "Syntax Error GraphQL request (2:19) Unexpected character \"'\".\n\n1: {\n2:   entries(query: {'content_type': 'sFzTZbSuM8coEwygeUYes'}) {\n                     ^\n3:     id\n",
      "locations": [
        {
          "line": 2,
          "column": 19
        }
      ]
    }
  ]
}
```

When I try to pass it as a string just got null on `entries`.

Any suggestions on how I can approach this ?.

**Comment by taion** [comment]
See https://github.com/taion/graphql-type-json/blob/9a8fe688c473493a8273f5f5b69c1d02d4474116/test/index.js#L59-L126

**Comment by juancabrera** [comment]
@taion I'm getting error even using literals, I'm using `express-graphql`, do you think it could be related to that ?

**Comment by taion** [comment]
It's not. Follow the example in the docs. The literals still have to look like nested GraphQL objects.

**Comment by taion** [comment]
In the test*

**Comment by langpavel** [comment]
@juancabrera `'` is not allowed in JSON, only `"`

**Comment by maxhudson** [comment]
I gave up on using it as an argument type, and just used strings as arguments instead (stringified json).
