### ISSUE TITLE
Default CommonJS export removed in latest release

### ISSUE THREAD

**Issue by hjvedvik** [taion/graphql-type-json#58]
The following code has been working fine until 0.2.3. Is it an intentional change? It' causing some problems for us at @gridsome (gridsome/gridsome#333) :)

```js
const GraphQLJSON = require('graphql-type-json')
```

Related #33

**Comment by taion** [comment]
oh gosh, okay, going to revert and republish

**Comment by taion** [comment]
reverted in v0.2.4

**Comment by hjvedvik** [comment]
That was fast! Thank you, works great now :)
