### ISSUE TITLE
0.1.3 and 0.1.2 contain no code on npm

### ISSUE THREAD

**Issue by benjie** [taion/graphql-type-json#6]
You've added `/lib` to .gitignore so npm automatically omits it on publish. You need a `.npmignore` file to bypass this.

Note however that if you track `lib` in source control (which seems dirty, I know) people can install directly from git.

**Comment by taion** [comment]
What are you talking about? https://unpkg.com/graphql-type-json@0.1.3/lib/

**Comment by benjie** [comment]
You're right - my apologies - I see now you're using the `files` field in `package.json` which my eyes skipped over earlier.

(When I filed this `npm` literally installed just the three files `LICENSE`, `README.md` and `package.json`; I resolved by installing `@0.1.1`; but now it works just fine... super weird.)

On the plus side, I didn't know about https://unpkg.com/ before!

**Comment by taion** [comment]
It's the former npmcdn. It's pretty neat. FWIW, it's probably better to use `package.files` rather than `.npmignore` – I find that whitelists usually work better than blacklists, since projects keep getting more and more random dotfiles as they age.

**Comment by benjie** [comment]
Yeah; I think I'll switch to using package.files in future; the whole npmignore thing is challenging to get right (you may have inferred I've been bitten by it in the past!)

**Comment by benjie** [comment]
So I figured out what happened when it just occurred again - I was accidentally installing 0.1.3 from git (not npm) and hence the file was not built and thus didn't exist.
