### ISSUE TITLE
Quoted Object Property Name

### ISSUE THREAD

**Issue by mcrawshaw** [taion/graphql-type-json#7]
The JSON spec allows for quoted property names

```
objectA["prop name"] = "blah"
```

However when I use with this library I receive an error
> Expected Name, found String "prop name"

I've tried to replicate by updating the test cases for this library and found it fails on the parse literal test with a different error.
> TypeError: Cannot read property 'value' of undefined

I'm not sure if this is a limitation of GraphQL-JS or this library, any assistance would be appreciated.

**Comment by taion** [comment]
Yeah, that doesn't work. This is just best-efforts given what's allowed in the GraphQL syntax.

**Comment by taion** [comment]
You might be able to use the syntax for non-inline variables.

**Comment by mcrawshaw** [comment]
No worries, will look into it, thanks for getting back to me.
