### ISSUE TITLE
Getting the following error

### ISSUE THREAD

**Issue by adviner** [taion/graphql-type-json#99]
I updated to the latest version of your lib and now when I start the web service using docker I get the following error:

For help, see: https://nodejs.org/en/docs/inspector
venueapiservice | /usr/local/lib/node_modules/graphql/jsutils/invariant.js:19
venueapiservice |     throw new Error(message);
venueapiservice |     ^
venueapiservice | 
venueapiservice | Error: Expected { __esModule: true, GraphQLJSON: JSON, default: JSON, GraphQLJSONObject: JSONObject } to be a GraphQL nullable type.
venueapiservice |     at invariant (/usr/local/lib/node_modules/graphql/jsutils/invariant.js:19:11)
venueapiservice |     at assertNullableType (/usr/local/lib/node_modules/graphql/type/definition.js:333:50)
venueapiservice |     at new GraphQLNonNull (/usr/local/lib/node_modules/graphql/type/definition.js:297:19)
venueapiservice |     at Object.<anonymous> (/var/venues/services/gql/mutation/application.js:70:10)
venueapiservice |     at Module._compile (internal/modules/cjs/loader.js:774:30)
venueapiservice |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
venueapiservice |     at Module.load (internal/modules/cjs/loader.js:641:32)
venueapiservice |     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
venueapiservice |     at Module.require (internal/modules/cjs/loader.js:681:19)
venueapiservice |     at require (internal/modules/cjs/helpers.js:16:16)

Any ideas on what is causing this error?  I commented out my use of any queries and mutations so I could see if the error occurs and it does.  I'm using the latest version of node and graphql 14.3.0.

Thanks

**Comment by taion** [comment]
We changed the exports in the latest version: https://github.com/taion/graphql-type-json/compare/v0.2.4...v0.3.0#diff-04c6e90faac2675aa89e2176d2eec7d8R24

**Comment by adviner** [comment]
I clicked on the link you provided but i'm not quite sure what is different.  Can you let me know please.

Thanks

**Comment by taion** [comment]
see https://github.com/taion/graphql-type-json#usage
